### ISSUE TITLE
Download ISO

### ISSUE THREAD

**Issue by xmha97** [y0umu/My-WinPE#1]
Hi,
How can I download the ISO of your Windows PE?
I'm busy and I can't get a build.

**Comment by y0umu** [comment]
As [stated](https://github.com/y0umu/My-WinPE#looks-cool-do-you-have-a-pre-built-thing-for-me-to-try-instantly) in README, there is legal risk. But I will try alternative ways to share the iso to those interested.

**Comment by xmha97** [comment]
Thanks, you can share your ISO on  	anonfiles.com

**Comment by y0umu** [comment]
iso image are at release page now.
